baseURL = "https://www.haojingque.com"
languageCode = "zh-cn"
theme = "jingzhe"
themesDir = "themes"
title = "好精雀-身心调节解决方案"
paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  showPostsOnHomepage = true
  addDot = true
  baseColor = "var(--background-color)"
  baseOffsetColor = "#eaeaea"
  headingColor = "#000"
  dotColor = "var(--text-highlight-color)"

[permalinks]
  posts = '/:slug.html'

[params.artalk]
    server="https://ping.sonss.cn"
    site="好精雀"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1